name: Canary Docker Build

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login into docker hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PW }}
      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Moonlight/Dockerfile
          push: true
          tags: moonlightpanel/moonlight:canary
          platforms: linux/amd64,linux/arm64