name: Test Build

on:
    push:
        branches: [ "main" ]
    pull_request:
        types:
            - closed
        branches: [ "main" ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Build Docker image
              run: docker build -t moonlightpanel/moonlight:${{ github.sha }} -f Moonlight/Dockerfile .